version: '3.8'

services:
  scraper:
    build: 
      context: .
      dockerfile: scrapers/Dockerfile
    command: python scrapers/crawl4ai_scraper.py

  fastapi:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - scraper
